services:

    scripts:
        container_name: scripts
        build: .
        mem_limit: 2G
        command: download.sh --output -
            "https://raw.githubusercontent.com/mbT-Infrastructure/docker-scripts/refs/heads/main/Readme.md"
        read_only: true
